---
- name: Copy files
  hosts: web_servers
  become: yes

  tasks:
  - name: Copy files
    copy:
      src: /tmp/copyfile.txt
      dest: /tmp/test1.txt
      owner: ec2-user
      group: ec2-user
      mode: "0640"

  - name: Copy remote file
    copy:
      src: /tmp/random.txt
      dest: /mnt/random.txt
      owner: ec2-user
      group: ec2-user
      mode: "0600"
      remote_src: yes 