---
- name: Create user
  hosts: all
  become: yes

  tasks:
  - name: Create User Alberto
    user:
      name: Alberto
      group: wheel
      append: yes
      comment: Alberto Diego

  - name: Create group Alberto
    group: 
      name: Alberto
      state: present