---
- name: Create a new user and a file in home directory
  hosts: localhost
  become: yes        
  tasks:
    - name: Create a new user named James
      user:
        name: James
        state: present
        shell: /bin/bash

    - name: Create a file in James' home directory
      copy:
        content: "This is James' file."
        dest: /home/James/jamesfile
        owner: James
        group: James
        mode: '0644'