---
- name: Create files
  hosts: Dev
  become: yes

  tasks: 
    - name: Create a "hello world" file
      file:
        path: /tmp/helloworld.txt
        owner: ec2-user
        group: ec2-user
        mode: "0644"
        state: touch

    - name: create a test directory
      file:
        path: /tmp/test
        owner: ec2-user
        group: ec2-user
        mode: "0755"
        state: directory