---
- name: setup http website
  hosts: web_servers
  become: yes

  task:
    - name: install httpd
      yum:
        state: latest
        name: httpd
    
    - name: start httpd
      service:
        name: httpd
        state: started
        enable: yes

    - name: edit html file
      lineinfile:
        path: /var/www/html/index.html    
        line: I created this with Ansible
        create: yes
        state: present