---
- name: setup http website
  hosts: web_servers
  become: yes
  vars_files:
   - my_variable.yaml

  task:
    - name: install httpd
      yum:
        state: latest
        name: "{{ httpd_package }}"
    
    - name: start httpd
      service:
        name: "{{ httpd_service }}"
        state: started
        enable: yes

    - name: edit html file
      lineinfile:
        path: /var/www/html/index.html    
        line: I created this with Ansible
        create: yes
        state: present