---
- name: Manage our services
  hosts: Dev
  become: yes

  tasks:
    - name: start firewalld
      service:
        name: firewalld
        state: started

    - name: Start and Enable httpd
        service:
          name: httpd
          state: started
          enabled: yes