---
- name: Set up an HTTP web server
  hosts: webservers
  become: yes
  tasks:
    - name: Install Apache
      package:
        name: httpd
        state: present

    - name: Create a simple HTML file
      copy:
        content: "I created this with Ansible"
        dest: /var/www/html/index.html
        mode: '0644'

    - name: Start and enable Apache
      service:
        name: httpd
        state: started
        enabled: yes
