---
- name: Update package cache
  apt:
    update_cache: yes
  when: ansible_os_family == "Debian"

- name: Update package cache
  yum:
    name: '*'
    state: latest
  when: ansible_os_family == "RedHat"

- name: Install Nginx
  apt:
    name: nginx
    state: present
  when: ansible_os_family == "Debian"

- name: Install Nginx
  yum:
    name: nginx
    state: present
  when: ansible_os_family == "RedHat"

- name: Start and enable Nginx
  service:
    name: nginx
    state: started
    enabled: true

- name: Create root directory
  file:
    path: "{{ root_directory }}"
    state: directory
    owner: www-data
    group: www-data
    mode: '0755'

- name: Deploy default Nginx configuration
  template:
    src: default.conf.j2
    dest: /etc/nginx/sites-available/default
  notify: restart nginx

- name: Ensure the configuration is linked
  file:
    src: /etc/nginx/sites-available/default
    dest: /etc/nginx/sites-enabled/default
    state: link