  - name: Install Firewalld
    yum:
      name: "{{ firewalld_package }}"
      state: present
    vars:
      firewalld_package:
      - firewalld 

  - name: Install Httpd
    yum: 
      name: "{{ httpd_package }}"
      state: present