---
- name: Install Nginx
  package:
    name: "{{ nginx_package }}"
    state: present
  
- name: Start and Enable Nginx
  service:
    name: "{{ nginx_service }}"
    state: started
    enabled: true

- name: Deploy custom index.html to document root
  copy:
    src: index.html
    dest: /var/www/html/index.html
    owner: "{{ user_apache }}"
    group: "{{ user_group }}"
    mode: '0644'