---
- name: Set up LAMP server
  hosts: webservers
  become: true

  tasks:
    - name: Install Apache
      package:
        name: "{{ apache_package }}"
        state: present

    - name: Start/Enable Apache
      service:
        name: httpd
        state: started
        enabled: true

    - name: Install MariaDB package
      package: 
        name: 
          - mariadb-server
        state: present

    - name: Start/Enable MariaDB service
      service:
        name: mariadb 
        state: started
        enabled: yes

    - name: Install PHP
      package:
        name:
         - php-common
         - php-fpm
         - php-gd
         - php-intl
         - php-json
         - php-mbstring
         - php-mysqlnd
         - php-xml
        state: present 

    - name: edit html file
      lineinfile:
        path: /var/www/html/index.php    
        line: I created this with Ansible
        create: yes
        state: present       