---
- name: Install Apache
  apt:
    name: apache2
    state: present
  when: ansible_os_family == "Debian"

- name: Install Apache
  yum:
    name: httpd
    state: present
  when: ansible_os_family == "RedHat"

- name: Ensure Apache is started and enabled
  service:
    name: "{{ 'apache2' if ansible_os_family == 'Debian' else 'httpd' }}"
    state: started
    enabled: true

- name: Deploy custom index.html
  template:
    src: index.html
    dest: /var/www/html/index.html
  notify: restart apache