---
- name: Update all packages on Debian-based systems
  apt:
    upgrade: dist
    update_cache: yes
  when: ansible_os_family == "Debian"

- name: Update all packages on RedHat-based systems
  yum:
    name: '*'
    state: latest
  when: ansible_os_family == "RedHat"

- name: Update all packages on Arch-based systems
  pacman:
    upgrade: yes
  when: ansible_os_family == "Archlinux"