---
- name: Install NRPE
  apt:
    name: nagios-nrpe-server
    state: present
    update_cache: yes

- name: Configure NRPE
  template:
    src: nrpe.cfg.j2
    dest: /etc/nagios/nrpe.cfg
  notify: restart nrpe

- name: Enable NRPE service
  service:
    name: nagios-nrpe-server
    state: started
    enabled: yes