---
- name: Set up LAMP server
  hosts: lamp_servers
  become: true
  tasks:

    - name: Update package cache
      apt:
        update_cache: yes
      when: ansible_os_family == "Debian"

    - name: Update package cache
      yum:
        name: '*'
        state: latest
      when: ansible_os_family == "RedHat"

    - name: Install Apache
      apt:
        name: apache2
        state: present
      when: ansible_os_family == "Debian"

    - name: Install Apache
      yum:
        name: httpd
        state: present
      when: ansible_os_family == "RedHat"

    - name: Start and enable Apache
      service:
        name: "{{ 'apache2' if ansible_os_family == 'Debian' else 'httpd' }}"
        state: started
        enabled: true

    - name: Install MySQL server
      apt:
        name: mysql-server
        state: present
      when: ansible_os_family == "Debian"

    - name: Install MySQL server
      yum:
        name: mysql-server
        state: present
      when: ansible_os_family == "RedHat"

    - name: Start and enable MySQL
      service:
        name: mysql
        state: started
        enabled: true

    - name: Install PHP and required modules
      apt:
        name: "{{ item }}"
        state: present
      with_items:
        - php
        - libapache2-mod-php
        - php-mysql
      when: ansible_os_family == "Debian"

    - name: Install PHP and required modules
      yum:
        name: "{{ item }}"
        state: present
      with_items:
        - php
        - php-mysqlnd
        - php-gd
      when: ansible_os_family == "RedHat"

    - name: Restart Apache to load PHP module
      service:
        name: "{{ 'apache2' if ansible_os_family == 'Debian' else 'httpd' }}"
        state: restarted