---
- name: Write a text into files
  hosts: Dev
  become: yes

  tasks:
    - name: Populate helloworld.txt
      lineinfile:
        path: /tmp/helloworld.txt
        create: yes
        owner: ec2-user
        group: ec2-user
        mode: "0644"
        line: hello world